server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/eduardo-braz/shop-Style_compass
          search-paths:
            - customer
            - checkout
            - catalog
            - history
